module.exports = {
  STEAM_GAMEPAGE_SCRIPT_LOADED: 'STEAM_GAMEPAGE_SCRIPT_LOADED',
  GET_APPS_INFO: 'GET_APPS_INFO',
  GET_APPS: 'GET_APPS',
  GET_APPS_COUNT: 'GET_APPS_COUNT',
  GET_NEW_APPS: 'GET_NEW_APPS',
  WEB_REQUEST_COMPLETED: 'WEB_REQUEST_COMPLETED',
  FETCH_GAMES: 'FETCH_GAMES'
}
